---
name: Verification tests

on: [push, pull_request]


jobs:
  build:
    name: Verify
    runs-on: ubuntu-latest  # container actions require GNU/Linux
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        submodules: 'recursive'
    - name: Install opam dependencies
      run: sudo apt update -y && sudo apt install -y pkg-config git rsync tar unzip m4 time curl ocaml build-essential bubblewrap gawk libgmp-dev python2.7 python3 python3-distutils libmpfr-dev
    - name: Install opam
      run: curl "https://github.com/ocaml/opam/releases/download/2.1.5/opam-2.1.5-x86_64-linux" -Lo /usr/local/bin/opam && chmod +x /usr/local/bin/opam
    - name: Setup opam
      run: opam init -y
    - name: Install dependencies
      run: OPAMFLAGS="-y" ./scripts/setup.sh
    - name: Print package versions
      run: eval $(opam env) && opam list
    - name: Opam switch export
      run: eval $(opam env) && opam switch export velliris-switch.txt && cat velliris-switch.txt
    - name: Check proofs
      run: eval $(opam env) && make -j
