---
name: Verification tests

on: [push, pull_request]


jobs:
  build:
    name: Verify
    runs-on: macos-13  # container actions require Mac OS 13
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false
        submodules: 'recursive'
    - name: Install brew
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    - name: Install opam dependencies
      run: brew update && brew install pkg-config git rsync gnu-tar unzip m4 gnu-time curl ocaml gawk gmp mpfr python@3.9 bubblewrap
    - name: Install opam
      run: brew install opam
    - name: Setup opam
      run: opam init -y
    - name: Install dependencies
      run: OPAMFLAGS="-y" ./scripts/setup.sh
    - name: Print package versions
      run: eval $(opam env) && opam list
    - name: Opam switch export
      run: eval $(opam env) && opam switch export --full velliris-switch.txt && cat velliris-switch.txt
    - name: Check proofs
      run: eval $(opam env) && make -j
